options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - rsync
      - -r
      - dags/
      - gs://us-central1-omni-composer-xxxx/dags

timeout: 300s
